# Generated by Django 5.0.6 on 2024-08-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_giftbox_category_delete_giftboxcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftbox",
            name="category",
        ),
    ]
