# Generated by Django 5.0.6 on 2024-08-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_giftbox_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftbox",
            name="category",
        ),
    ]
