# Generated by Django 5.0.6 on 2024-08-14 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0006_giftboxcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftbox",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce.category",
            ),
        ),
        migrations.DeleteModel(
            name="GiftBoxCategory",
        ),
    ]
