# Generated by Django 5.0.6 on 2024-08-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0008_alter_order_customer_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_status",
            field=models.CharField(
                choices=[("cart", "Cart"), ("real", "Real")],
                default="cart",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
