# Generated by Django 5.0.6 on 2024-10-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0010_orderitem_description_orderitem_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
